version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nowex_postgres
    environment:
      POSTGRES_DB: nowex_development
      POSTGRES_USER: nowex_user
      POSTGRES_PASSWORD: Mezr@1360
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - nowex_network

  redis:
    image: redis:7-alpine
    container_name: nowex_redis
    ports:
      - "6379:6379"
    networks:
      - nowex_network

  backend:
    build: 
     context: ./backend
     dockerfile: Dockerfile
    container_name: nowex_backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_USER=nowex_user
      - POSTGRES_PASSWORD=Mezr@1360
      - POSTGRES_DB=nowex_development
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your_super_secret_key_change_in_production
    depends_on:
      - postgres
      - redis
    # حذف این خط - volume برای sync
    # volumes:
    #   - ./backend:/app
    networks:
      - nowex_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  nowex_network:
    driver: bridge